/****************************************************************************************
* File: main_hack.cpp
*
* Description: Configures and starts the Quadcopter
* main.c is generated by STM32CubeMX, so we need the actual main file to be named differently
*
* Created by Matt Olson
****************************************************************************************/

/*---------------------------------------------------------------------------------------
*                                       INCLUDES
*--------------------------------------------------------------------------------------*/
#include <cstdio>

#include "main.h"
#include "led.h"
#include "spi.h"
#include "lis3dsh.h"

/*---------------------------------------------------------------------------------------
*                                   LITERAL CONSTANTS
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                        TYPES
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                   MEMORY CONSTANTS
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                      VARIABLES
*--------------------------------------------------------------------------------------*/
LED green_led(GPIOD, GPIO_PIN_12);
LED orange_led(GPIOD, GPIO_PIN_13);
LED red_led(GPIOD, GPIO_PIN_14);
LED blue_led(GPIOD, GPIO_PIN_15);

SPI accel_spi(&hspi1, ACCEL_CS_GPIO_Port, ACCEL_CS_Pin);
LIS3DSH accel(&accel_spi);

/*---------------------------------------------------------------------------------------
*                                     PROCEDURES
*--------------------------------------------------------------------------------------*/

/*****************************************************************************
* Function: delay
*
* Description: Busy waits for a set number of miliseconds
*****************************************************************************/
void delay(uint32_t ms)
{
    uint32_t endTick = HAL_GetTick() + ms;
    while (endTick > HAL_GetTick())
    {
        asm("nop");
    }
}

/*****************************************************************************
* Function: main
*
* Description: The main loop of the quadcopter
*****************************************************************************/
int main(void)
{
    /* MCU Configuration--------------------------------------------------------*/
    InitHardware();

    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();

    /* Initialize all configured peripherals */
    accel.Init();

    while(true)
    {
        accel.UpdateData();
        if (accel.Y > 0)
        {
            orange_led.On();
            blue_led.Off();
        }
        else
        {
            orange_led.Off();
            blue_led.On();
        }
        if (accel.X > 0)
        {
            green_led.Off();
            red_led.On();
        }
        else
        {
            green_led.On();
            red_led.Off();
        }
    }
}
