/****************************************************************************************
* File: main_hack.cpp
*
* Description: Configures and starts the Quadcopter
* main.c is generated by STM32CubeMX, so we need the actual main file to be named differently
*
* Created by Matt Olson
****************************************************************************************/

/*---------------------------------------------------------------------------------------
*                                       INCLUDES
*--------------------------------------------------------------------------------------*/
#include <cstdio>

#include "main.h"
#include "led.h"
#include "i2c.h"
#include "lsm303agr.h"

/*---------------------------------------------------------------------------------------
*                                   LITERAL CONSTANTS
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                        TYPES
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                   MEMORY CONSTANTS
*--------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------
*                                      VARIABLES
*--------------------------------------------------------------------------------------*/
LED led_W(LED_W_GPIO_Port, LED_W_Pin);
LED led_N(LED_N_GPIO_Port, LED_N_Pin);
LED led_E(LED_E_GPIO_Port, LED_E_Pin);
LED led_S(LED_S_GPIO_Port, LED_S_Pin);

I2C accel_i2c(&hi2c1);
LSM303AGR accel(&accel_i2c);

/*---------------------------------------------------------------------------------------
*                                     PROCEDURES
*--------------------------------------------------------------------------------------*/

/*****************************************************************************
* Function: delay
*
* Description: Busy waits for a set number of miliseconds
*****************************************************************************/
void delay(uint32_t ms)
{
    uint32_t endTick = HAL_GetTick() + ms;
    while (endTick > HAL_GetTick())
    {
        asm("nop");
    }
}

/*****************************************************************************
* Function: main
*
* Description: The main loop of the quadcopter
*****************************************************************************/
int main(void)
{
    /* MCU Configuration--------------------------------------------------------*/
    InitHardware();

    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();

    /* Initialize all configured peripherals */
    accel.Init();

    while(true)
    {
        accel.UpdateData();
        if (accel.Y > 0)
        {
            led_N.On();
            led_S.Off();
        }
        else
        {
            led_N.Off();
            led_S.On();
        }
        if (accel.X > 0)
        {
            led_W.Off();
            led_E.On();
        }
        else
        {
            led_W.On();
            led_E.Off();
        }
    }
}
